### Unique Categories Extracted
The categories exactly as named in the PDFs (noting that the school PDF has no explicit categories, so "School" is inferred based on content; others are direct):

- School
- Mosque
- Commercial Building
- Stores and Factory
- Public Project

### SQL Insertion Statements
Here are the SQL INSERT statements for all projects extracted from the four PDFs. Each is a separate INSERT for ease of execution. Slugs are generated uniquely based on title, year (or 'school' for school projects), and location. Missing fields are set to NULL as specified.

INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('al-aqsa-preparatory-school-for-girls-school-ain-khaled-doha', 'Al Aqsa Preparatory School for Girls', NULL, 'School', 'Ain Khaled, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('audio-education-complex-for-girls-school-old-airport-area-doha', 'Audio Education Complex for Girls', NULL, 'School', 'Old Airport Area, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('fatima-al-zahra-preparatory-school-for-girls-school-al-mansoura-doha', 'Fatima Al Zahra Preparatory School for Girls', NULL, 'School', 'Al Mansoura, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('qatar-primary-school-for-boys-school-bin-mahmoud-doha', 'Qatar Primary School for Boys', NULL, 'School', 'Bin Mahmoud, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('al-shurooq-model-school-for-boys-school-al-gharafa-doha', 'Al Shurooq Model School for Boys', NULL, 'School', 'Al Gharafa, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('al-wakra-primary-school-for-girls-school-al-wakra-qatar', 'Al Wakra Primary School for Girls', NULL, 'School', 'Al Wakra, Qatar', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('abdul-rahman-bin-auf-school-for-boys-school-al-sadd-doha', 'Abdul Rahman Bin Auf School for Boys', NULL, 'School', 'Al Sadd, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('jassim-bin-hamad-secondary-school-for-boys-school-al-sadd-doha', 'Jassim Bin Hamad Secondary School for Boys', NULL, 'School', 'Al Sadd, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('arwa-bint-abdul-muttalib-secondary-school-for-girls-school-al-wakra-qatar', 'Arwa Bint Abdul Muttalib Secondary School for Girls', NULL, 'School', 'Al Wakra, Qatar', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('omar-bin-abdulaziz-secondary-school-for-boys-school-al-hilal-doha', 'Omar Bin Abdulaziz Secondary School for Boys', NULL, 'School', 'Al Hilal, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('musab-bin-umair-secondary-school-for-boys-school-al-thumama-doha', 'Musab Bin Umair Secondary School for Boys', NULL, 'School', 'Al Thumama, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('rawdat-rashed-primary-school-for-boys-school-rawdat-rashed-doha', 'Rawdat Rashed Primary School for Boys', NULL, 'School', 'Rawdat Rashed, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('rawdat-rashed-secondary-school-for-boys-school-rawdat-rashed-doha', 'Rawdat Rashed Secondary School for Boys', NULL, 'School', 'Rawdat Rashed, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('al-bayan-school-school-al-waab-doha', 'Al Bayan School', NULL, 'School', 'Al Waab, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('al-wukair-school-school-al-wukair-qatar', 'Al Wukair School', NULL, 'School', 'Al Wukair, Qatar', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('musab-bin-umair-school-for-boys-school-al-thumama-doha', 'Musab Bin Umair School for Boys', NULL, 'School', 'Al Thumama, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('umm-qarn-school-school-umm-qarn-qatar', 'Umm Qarn School', NULL, 'School', 'Umm Qarn, Qatar', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('al-sailiya-secondary-school-for-boys-school-al-sailiya-doha', 'Al Sailiya Secondary School for Boys', NULL, 'School', 'Al Sailiya, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('ibn-taymiyyah-school-school-al-rayyan-doha', 'Ibn Taymiyyah School', NULL, 'School', 'Al Rayyan, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('al-shahaniya-independent-school-school-al-shahaniya-qatar', 'Al Shahaniya Independent School', NULL, 'School', 'Al Shahaniya, Qatar', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('al-shahaniya-secondary-school-school-al-shahaniya-qatar', 'Al Shahaniya Secondary School', NULL, 'School', 'Al Shahaniya, Qatar', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('arwa-bint-abdul-muttalib-school-school-al-wakra-qatar', 'Arwa Bint Abdul Muttalib School', NULL, 'School', 'Al Wakra, Qatar', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('al-brouq-primary-school-for-girls-school-al-rayyan-doha', 'Al Brouq Primary School for Girls', NULL, 'School', 'Al Rayyan, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('muaither-primary-school-for-boys-school-muaither-doha', 'Muaither Primary School for Boys', NULL, 'School', 'Muaither, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('omar-bin-abdulaziz-school-school-al-hilal-doha', 'Omar Bin Abdulaziz School', NULL, 'School', 'Al Hilal, Doha', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('rafidah-bint-kaab-school-for-girls-school-al-wakra-qatar', 'Rafidah Bint Kaab School for Girls', NULL, 'School', 'Al Wakra, Qatar', 'The Ministry of Education', 'Mesopotamia For General Contracting', 'The Ministry of Education', NULL, NULL, NULL, 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('mosque-nuaija-2023-nuaija', 'Mosque – Nuaija', NULL, 'Mosque', 'Nuaija', NULL, 'Mesopotamia for General Contracting', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-mdm5-with-imam-house-type-5a-2023-rawdat-egdam', 'Proposed Mosque M-DM5 with Imam House Type 5A', NULL, 'Mosque', 'Rawdat Egdam', NULL, 'Rawdet El Hamam for General Construction Co.', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('mosque-qatar-mall-rawdat-al-hamamam-2023-qatar-mall', 'Mosque – Qatar Mall (Rawdat Al Hamamam)', NULL, 'Mosque', 'Qatar Mall', NULL, 'Rawdet El Hamam for General Construction Co.', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-m126a-with-imam-house-type-5a-2023-rawdat-el-gehena', 'Proposed Mosque M-126A with Imam House Type 5A', NULL, 'Mosque', 'Rawdat El Gehena', NULL, 'Rivera Trading & Contracting Co.', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('mosque-al-sakhama-2023-al-sakhama', 'Mosque – Al Sakhama', NULL, 'Mosque', 'Al Sakhama', NULL, 'Royal Abjar', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('mosque-116a-2023-al-wukair', 'Mosque 116-A', NULL, 'Mosque', 'Al Wukair', NULL, 'Amad Construction', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('compound-villa-al-aziziya-2023-al-aziziya', 'Compound Villa – Al Aziziya', NULL, 'Commercial Building', 'Al Aziziya', NULL, 'Al Msaken', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-asphalt-works-for-book-store-gym-el-ebb-k125-2023-el-ebb-k125', 'Proposed Asphalt Works for Book Store & Gym (EL EBB K125)', NULL, 'Commercial Building', 'El EBB (K125)', NULL, 'K.B.R. Qatar Trading & Contracting', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-prime-power-logistic-facility-2023-gharry-el-samer', 'Proposed Prime Power Logistic Facility', NULL, 'Stores and Factory', 'Gharry El Samer', NULL, 'Gulf Falcon Contracting Co.', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('commercial-complex-2023-al-wakra', 'Commercial Complex', NULL, 'Commercial Building', 'Al Wakra', NULL, 'Al Jazira Building & Construction', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-food-storage-offices-showroom-labour-camp-2023-al-wakra', 'Proposed Food Storage, Offices, Showroom & Labour Camp', NULL, 'Stores and Factory', 'Al Wakra', NULL, 'Shard Projects Company', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('al-hadarma-parking-2023-rayyan', 'Al Hadarma Parking', NULL, 'Public Project', 'Rayyan', NULL, 'Daar Al Rayyan Investment', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('farm-183-internal-road-works-p2206-2023-al-wakra', 'Farm 183 – Internal Road Works (P-2206)', NULL, 'Public Project', 'Al Wakra', NULL, 'Westfield Engineering Construction W.L.L', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('villa-sheikha-aisha-bin-khalifa-2023-doha', 'Villa Sheikha Aisha Bin Khalifa', NULL, 'Commercial Building', 'Doha', NULL, 'Westfield Engineering Construction W.L.L', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('compound-villa-24-2023-umm-salal', 'Compound Villa 24', NULL, 'Commercial Building', 'Umm Salal', NULL, 'Golden Beach Trading', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('al-wakra-logistic-2023-al-wakra', 'Al Wakra Logistic', NULL, 'Stores and Factory', 'Al Wakra', NULL, 'FBA Engineering & Contracting', NULL, NULL, NULL, '2023', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-residential-complex-2024-al-kheesa', 'Proposed Residential Complex', NULL, 'Commercial Building', 'Al Kheesa', NULL, 'Qasr El Shamoukh Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('building-material-store-showroom-administrative-office-labor-accommodation-services-1-2-2024-birkat-al-awamer', 'Building Material Store, Showroom, Administrative Office & Labor Accommodation (Services 1 & 2)', NULL, 'Stores and Factory', 'Birkat Al Awamer', NULL, 'Al Kamal International Group', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('galvanizing-plant-project-site-2024-new-industrial-area', 'Galvanizing Plant Project Site', NULL, 'Stores and Factory', 'New Industrial Area', NULL, 'Rational Trading & Contracting W.L.L', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-m126a-with-imam-house-5a-2024-bani-hajer', 'Proposed Mosque (M126A) with Imam House (5A)', NULL, 'Mosque', 'Bani Hajer', NULL, 'Kemet for Trading & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-with-two-imam-houses-type-a5-2024-al-sheehaniya', 'Proposed Mosque with Two Imam Houses (Type A/5)', NULL, 'Mosque', 'Al Sheehaniya', NULL, 'Rawdat Al Hamama', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('thea-live-work-play-2024-lusail-laqtaifa', 'Thea Live Work Play', NULL, 'Commercial Building', 'Lusail / Laqtaifa', NULL, 'Homeco General Construction Trading Co.', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('car-storage-guard-room-2024-birkat-al-awamer', 'Car Storage & Guard Room', NULL, 'Stores and Factory', 'Birkat Al Awamer', NULL, 'Al Mana Group', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-parking-2024-rawdat-al-hamama', 'Proposed Mosque Parking', NULL, 'Mosque', 'Rawdat Al Hamama', NULL, 'Royal Abjar Trading & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('maintenance-works-at-al-noor-petrol-station-2024-bu-sidra', 'Maintenance Works at Al Noor Petrol Station', NULL, 'Commercial Building', 'Bu Sidra', NULL, 'Qatar Star Enterprises & Services Co.', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('cement-factory-2024-industrial-area', 'Cement Factory', NULL, 'Stores and Factory', 'Industrial Area', NULL, 'Greater Doha Trading & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-play-area-2024-al-gharrafa', 'Proposed Play Area', NULL, 'Public Project', 'Al Gharrafa', NULL, 'Artline Trading & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-parking-2024-al-wukair', 'Proposed Mosque Parking', NULL, 'Mosque', 'Al Wukair', NULL, 'Maha Al Khaleej for Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-villa-2024-al-wukair', 'Proposed Villa', NULL, 'Commercial Building', 'Al Wukair', NULL, 'Greater Doha Trading & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-villa-2024-al-kheesa', 'Proposed Villa', NULL, 'Commercial Building', 'Al Kheesa', NULL, 'Contraco W.L.L', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-1404-2024-al-sakhama', 'Proposed Mosque 1404', NULL, 'Mosque', 'Al Sakhama', NULL, 'Techno Fab Trading & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-compound-2024-ain-khalid', 'Proposed Compound', NULL, 'Public Project', 'Ain Khalid', NULL, 'Qatar Red Crescent', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('logistic-park-2024-birkat-al-awamer', 'Logistic Park', NULL, 'Stores and Factory', 'Birkat Al Awamer', NULL, 'FBA Engineering & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('external-works-2024-birkat-al-awamer', 'External Works', NULL, 'Public Project', 'Birkat Al Awamer', NULL, 'Future Company', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('compound-villa-g1ph-guard-room-2024-doha', 'Compound Villa (G+1+P.H) + Guard Room', NULL, 'Commercial Building', 'Doha', NULL, 'Mezab Trading & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('asphalt-works-villaggio-mall-part-1-2024-villaggio-mall-al-aziziyah', 'Asphalt Works – Villaggio Mall (Part 1)', NULL, 'Public Project', 'Villaggio Mall, Al Aziziyah', NULL, 'International Decoration & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('asphalt-works-villaggio-mall-part-2-2024-villaggio-mall-al-aziziyah', 'Asphalt Works – Villaggio Mall (Part 2)', NULL, 'Public Project', 'Villaggio Mall, Al Aziziyah', NULL, 'International Decoration & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('asphalt-works-villaggio-mall-part-3-2024-villaggio-mall-al-aziziyah', 'Asphalt Works – Villaggio Mall (Part 3)', NULL, 'Public Project', 'Villaggio Mall, Al Aziziyah', NULL, 'International Decoration & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('asphalt-works-villaggio-mall-part-4-2024-villaggio-mall-al-aziziyah', 'Asphalt Works – Villaggio Mall (Part 4)', NULL, 'Public Project', 'Villaggio Mall, Al Aziziyah', NULL, 'International Decoration & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-modification-mosque-mdm5-with-two-imam-houses-type-5a-2024-al-kharaitiyat', 'Proposed Modification Mosque M-DM5 with Two Imam Houses Type 5A', NULL, 'Mosque', 'Al Kharaitiyat', NULL, 'Royal Stone Trading & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-commercial-buildings-mosque-2024-birkat-al-awamer', 'Proposed Commercial Buildings & Mosque', NULL, 'Public Project', 'Birkat Al Awamer', NULL, 'Raptor One Contracting & Services', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-villa-2024-al-ghashamiya', 'Proposed Villa', NULL, 'Commercial Building', 'Al Ghashamiya', NULL, 'Daran Construction & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-imam-house-eid-prayer-room-pin-70151256-2024-doha', 'Proposed Mosque, Imam House & Eid Prayer Room (PIN: 70151256)', NULL, 'Mosque', 'Doha', NULL, 'Millennium Trading & Contracting Co.', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-m117a-eid-prayer-yard-imam-house-type-5a-2024-al-kheesa', 'Proposed Mosque M117A + Eid Prayer Yard & Imam House Type 5A', NULL, 'Mosque', 'Al Kheesa', NULL, 'Jamatco for Trading & Contracting', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-car-parking-for-masjid-no-060-2024-doha', 'Proposed Car Parking for Masjid No. 060', NULL, 'Mosque', 'Doha', NULL, 'Al Majlis Contracting & Building Co.', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-office-gf-workshop-gm-2024-doha', 'Proposed Office (G+F) & Workshop (G+M)', NULL, 'Stores and Factory', 'Doha', NULL, 'Tabadol Trading & Contracting Est.', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('decoration-workshop-decoration-supplies-store-labor-accommodation-building-2024-birkat-al-awamer', 'Decoration Workshop, Decoration Supplies Store & Labor Accommodation Building', NULL, 'Commercial Building', 'Birkat Al Awamer', NULL, 'Yazwah Projects', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-mdm5-with-imam-house-type-5a-2024-umm-salal', 'Proposed Mosque MDM-5 with Imam House Type 5A', NULL, 'Mosque', 'Umm Salal', NULL, 'Shard Project Company', NULL, NULL, NULL, '2024', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-residential-complex-2025-al-kheesa', 'Proposed Residential Complex', NULL, 'Commercial Building', 'AL KHEESA', NULL, 'Qasr El Shamoukh Contracting', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('building-material-store-showroom-administrative-office-labor-accommodation-services-1-2-2025-birkat-al-awamer', 'Building Material Store, Showroom, Administrative Office & Labor Accommodation (Services 1 & 2)', NULL, 'Stores and Factory', 'Birkat Al Awamer', NULL, 'Al Kamal International Group', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('galvanizing-plant-project-site-2025-new-industrial-area', 'Galvanizing Plant Project Site', NULL, 'Stores and Factory', 'New Industrial Area', NULL, 'Rational Trading & Contracting W.L.L', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-m126a-with-imam-house-5a-2025-bani-hajer', 'Proposed Mosque (M126A) with Imam House (5A)', NULL, 'Mosque', 'Bani Hajer', NULL, 'Kemet for Trading & Contracting', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-with-two-imam-houses-type-a5-2025-al-sheehaniya', 'Proposed Mosque with Two Imam Houses (Type A/5)', NULL, 'Mosque', 'Al Sheehaniya', NULL, 'Rawdat Al Hamama', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('thea-live-work-play-2025-laqtefa', 'Thea Live Work Play', NULL, 'Commercial Building', 'Laqtefa', NULL, 'Homeco General Construction Trading Co.', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('car-storage-guard-room-2025-birkat-al-awamer', 'Car Storage & Guard Room', NULL, 'Stores and Factory', 'Birkat Al Awamer', NULL, 'Al Mana Group', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-parking-2025-rawdat-al-hamama', 'Proposed Mosque Parking', NULL, 'Mosque', 'Rawdat Al Hamama', NULL, 'Royal Abjar Trading & Contracting', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('maintenance-works-at-al-noor-petrol-station-2025-bu-sidra', 'Maintenance Works at Al Noor Petrol Station', NULL, 'Commercial Building', 'Bu Sidra', NULL, 'Qatar Star Enterprises & Service Co.', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('cement-factory-2025-industrial-area', 'Cement Factory', NULL, 'Stores and Factory', 'Industrial Area', NULL, 'Greater Doha Trading & Contracting', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-play-area-2025-al-gharrafa', 'Proposed Play Area', NULL, 'Public Project', 'Al Gharrafa', NULL, 'Artline Trading & Contracting', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-parking-2025-al-wukair', 'Proposed Mosque Parking', NULL, 'Mosque', 'Al Wukair', NULL, 'Maha Al Khaleej for Contracting', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-villa-2025-al-wukair', 'Proposed Villa', NULL, 'Commercial Building', 'Al Wukair', NULL, 'Greater Doha Trading & Contracting', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-villa-2025-al-kheesa', 'Proposed Villa', NULL, 'Commercial Building', 'AL KHEESA', NULL, 'Contraco W.L.L', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-mosque-1404-2025-al-sakhama', 'Proposed Mosque 1404', NULL, 'Mosque', 'Al Sakhama', NULL, 'Techno Fab Trading & Contracting', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);
INSERT INTO projects (slug, title, description, category, location, client, main_contractor, consultant, area, value, year, status, featured, images, created_by) VALUES ('proposed-compound-2025-ain-khalid', 'Proposed Compound', NULL, 'Public Project', 'Ain Khalid', NULL, 'Qatar Red Crescent', NULL, NULL, NULL, '2025', 'completed', 0, NULL, NULL);